source 'https://github.com/CocoaPods/Specs.git'

target 'WLXBluetoothDevice', :exclusive => true do
  pod "WLXBluetoothDevice", :path => "../"
  pod 'CocoaLumberjack', '~>2.0.0-rc'
end

target 'Tests', :exclusive => true do
  pod "WLXBluetoothDevice", :path => "../"

  pod 'Specta', '~> 0.3.2'
  pod 'Expecta'
  pod 'OCMockito', '~> 1.0'
end
