language: objective-c
osx_image: xcode7.2
before_install: sudo gem install bundler
script: REPO_SLUG="$TRAVIS_REPO_SLUG" PULL_REQUEST="$TRAVIS_PULL_REQUEST" FORCE_CARTHAGE_VERSION=true script/cibuild
branches:
  only:
  - master
env:
  global:
  - secure: D7z0DMvnWeH2scCvlkDZADdt+CSov1W7Db5oOf1A2/qUrTH8cFR3p7zz4lvxXrksIM5J3+HJj+mIp3w1s3XoNB3hZNLd12Zu1UyVrdcHABpCPZJjl2XPm1Xj36UDPWsw2fZlDZiKPLo43BKzWeKIuIQrRWelv/nnUHKUAS6qR4Q=
  - secure: GoN7Ignb8ygd1CqJBoA1rf+iKi8HS6ZrMGcnYR7aElmCF8izfS2rz0rt67ERx0Z1SDX9AwfNM+GVYU9Q0mDkV3+Hzs+5Qa7C5wqWJhW60DI/0gYPwgXtknCRfumysSskKBvvVQuWyEcdiGiKAyx60yUGpwVKfv5txCyKX+8F/KU=
