# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
podfile: Example/Podfile
before_install:
  - bundle install
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - cd Example && rake xbuild:clean xbuild:test
after_success:
  - cd && slather
