language: objective-c
osx_image: xcode6.4
script: script/cibuild
branches:
  only:
  - master
env:
  global:
    secure: D7z0DMvnWeH2scCvlkDZADdt+CSov1W7Db5oOf1A2/qUrTH8cFR3p7zz4lvxXrksIM5J3+HJj+mIp3w1s3XoNB3hZNLd12Zu1UyVrdcHABpCPZJjl2XPm1Xj36UDPWsw2fZlDZiKPLo43BKzWeKIuIQrRWelv/nnUHKUAS6qR4Q=
