# reference: http://www.objc.io/issue-6/travis-ci.html

rvm:
  - 2.1.2
language: objective-c
osx_image: xcode63
before_install:
  - bundle install
  - brew update
  - brew install carthage
  - carthage bootstrap --verbose
script:
  - scripts/test.sh && bundle exec pod lib lint --quick
#after_success:
#  - bundle exec slather
